### ISSUE TITLE
Make Pickle Icon for Lab

### ISSUE THREAD

**Issue by gabrielgellner** [McCannLab/McCannLab.github.io#1]

**Comment by KevCaz** [comment]
I think it is a great idea what about something like [pickle rick](https://sillypunter.com/products/rick-and-morty-i-am-pickle-rick) more fishy and more McCanny?

**Comment by gabrielgellner** [comment]
Okay a quick mockup. Need to fade the pickle a bit, but what do people think?

![icon](https://user-images.githubusercontent.com/9829364/46928910-cea57380-d00a-11e8-9687-b128bb472467.png)

**Comment by KevCaz** [comment]
ahaha looks good! I guess you should survey elsewhere as GH users are the minority in the Lab (hopefully this will change at some point).

**Comment by gabrielgellner** [comment]
the will come for the mcann pickle-fish and stay for the github goodness...

**Comment by gabrielgellner** [comment]
Move conversation to LabAdmin.
