### ISSUE TITLE
Bad certificate - issue in firefox

### ISSUE THREAD

**Issue by cgreysongaito** [McCannLab/McCannLab.github.io#13]
![Screenshot_2019-05-15_11-04-36](https://user-images.githubusercontent.com/6303460/57786480-8ca7f180-7701-11e9-9d5d-7d3be357245c.png)

Not sure how to fix it. Thought I'd let you know.

**Comment by KevCaz** [comment]
I thought this was no longer an issue. I'll need to know if this is also a problem for other people. First time I encountered this issue, I simply "accepted" the risk!

**Comment by KevCaz** [comment]
2 notes here: 
- I'm using firefox and chrome on my debian machine and I've tries with chrome on another computer with MacOS installed and it works;
- Can you try to delete the cache of your firefox (just in case).
