### ISSUE TITLE
Lab meeting 24 Oct 2018 - Git & co

### ISSUE THREAD

**Issue by KevCaz** [McCannLab/McCannLab.github.io#2]
Write a post about it. I'll draft it, @gabrielgellner when I'm done would you mind reviewing the post (again a quick one).

See 
- https://github.com/McCannLab/LabAdmin/issues/6
- https://github.com/McCannLab/LabAdmin/issues/4

**Comment by gabrielgellner** [comment]
Heck ya. Will be ready when you are. I have some simple (bullet point notes) if that is useful.

**Comment by KevCaz** [comment]
> I have some simple (bullet point notes) if that is useful.

Yep! You can either add them here or in `content/post/post_0001.md` via a commit! :smile:

**Comment by gabrielgellner** [comment]
You seem to be using gitflow, do you want me to branch off devel first? Or just get dirty and commit on devel directly?

**Comment by KevCaz** [comment]
Opps I forgot to mention this: 

The master branch is where the site is deployed, so you push on devel and if the build passes then the site will be deployed by Travis! So no git flow, but commit on devel!  The default branch is devel!

**Comment by KevCaz** [comment]
Draft is done https://mccannlab.github.io/post/2018/05/18/git-github--gitkraken/ (I made a few comments on the .md file so you know what I have in mind, feel free to edit as much as you want) + I added a few guidelines to use the website in the readme. 

@gabrielgellner do you know how easy it is to deal with submodules in GitKraken?

**Comment by gabrielgellner** [comment]
My only worry for the context is that it links to a lot of semi advanced tutorials (for our audience) which might cause some worry. I think anything that mentions PR or branches at this point is likely not going to help us :) Could we have a second page with further information so we keep the beginning nice and applied? Similarly for talking about Travis and web services. I might be off the mark but I think this will all seem very confusing to most who have never used any VCS before.

**Comment by KevCaz** [comment]
Ok, let's keep the advanced material for another post!
