### ISSUE TITLE
git clone submodules - repeat

### ISSUE THREAD

**Issue by cgreysongaito** [McCannLab/McCannLab.github.io#8]
Repetition of below
git clone --recurse-submodules https://github.com/McCannLab/McCannLab.github.io.git

But if you intend to rebuild the website locally then you need to include the submodules using the --recurse-submodules option.

git clone --recurse-submodules https://github.com/McCannLab/McCannLab.github.io.git

**Comment by KevCaz** [comment]
Thanks @cgreysongaito.
